# ==============================================================================
# Survey debiasing post: additional figures
# ==============================================================================
#
# Produces two figures for the Substack post that complement the common-support
# plot already generated by survey_debiasing_marketplace.R:
#
#   figures/selection_geometry.png
#     2D scatter on monthly_app_opens x annual_spend showing how the 1,001
#     respondents sit inside the 150,000-user invited cloud. Fills the
#     "visual brief here" slot at the end of "Don't fall for the survey
#     response trap."
#
#   figures/respondent_vs_invited.png
#     Dumbbell comparing respondent and invited means on four covariates
#     (age, % female, annual spend, monthly app opens). Fills the "visual
#     brief here" slot in Step 1 of the worked example.
#
# Reads data/survey_population.csv. Run generate_survey_data.R first.
#
# Dependencies: tidyverse, scales
# ==============================================================================

library(tidyverse)
library(scales)

if (!file.exists("data/survey_population.csv")) {
  stop("data/survey_population.csv not found. Run generate_survey_data.R first.")
}

population <- read_csv("data/survey_population.csv", show_col_types = FALSE)

dir.create("figures", showWarnings = FALSE)

# ------------------------------------------------------------------------------
# Figure 1: selection geometry
# ------------------------------------------------------------------------------
#
# Background: all 150,000 invited users as a light-grey cloud.
# Foreground: the 1,001 respondents in red.
# The respondent cloud should visibly sit in the upper-right (high app opens,
# high spend) corner of the invited cloud - the geometric picture of
# "who-answers is correlated with who-you-are."

selection_geometry <- ggplot() +
  geom_point(
    data  = population,
    aes(x = monthly_app_opens, y = annual_spend, colour = "All invited"),
    size  = 0.3,
    alpha = 0.35
  ) +
  geom_point(
    data  = filter(population, responded == 1),
    aes(x = monthly_app_opens, y = annual_spend, colour = "Respondents"),
    size  = 0.9,
    alpha = 0.85
  ) +
  scale_colour_manual(
    values = c("All invited" = "grey75", "Respondents" = "#EF4444"),
    guide  = guide_legend(override.aes = list(size = 3, alpha = 1))
  ) +
  scale_y_log10(labels = dollar_format(accuracy = 1)) +
  scale_x_continuous(breaks = pretty_breaks(n = 6)) +
  labs(
    title    = "Respondents sit in the high-engagement, high-spend corner",
    subtitle = "150,000 invited users (grey) vs. the 1,001 who responded (red)",
    x        = "Monthly app opens",
    y        = "Annual spend (log scale)",
    colour   = NULL,
    caption  = "Each dot is one user. The respondent cloud is a self-selected slice of the invited cloud,\nnot a random sample of it."
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position = "top",
    plot.title      = element_text(face = "bold"),
    plot.caption    = element_text(hjust = 0, colour = "grey30")
  )

ggsave(
  filename = "figures/selection_geometry.png",
  plot     = selection_geometry,
  width    = 8,
  height   = 5,
  dpi      = 200
)

cat("Saved figures/selection_geometry.png\n")

# ------------------------------------------------------------------------------
# Figure 2: respondent vs. invited means on four covariates
# ------------------------------------------------------------------------------
#
# Dumbbell plot with one facet per covariate so each keeps its native units.
# Gap length between the two dots shows how much respondents deviate from
# the invited population on each observable.

summary_long <- bind_rows(
  population %>%
    summarise(
      Age                 = mean(age),
      `% Female`          = mean(female) * 100,
      `Annual spend`      = mean(annual_spend),
      `Monthly app opens` = mean(monthly_app_opens)
    ) %>%
    mutate(group = "Invited (150,000)"),
  population %>%
    filter(responded == 1) %>%
    summarise(
      Age                 = mean(age),
      `% Female`          = mean(female) * 100,
      `Annual spend`      = mean(annual_spend),
      `Monthly app opens` = mean(monthly_app_opens)
    ) %>%
    mutate(group = "Respondents (1,001)")
) %>%
  pivot_longer(cols = -group, names_to = "covariate", values_to = "value") %>%
  mutate(
    covariate = factor(
      covariate,
      levels = c("Age", "% Female", "Annual spend", "Monthly app opens")
    ),
    label = case_when(
      covariate == "Age"                ~ sprintf("%.0f yrs", value),
      covariate == "% Female"           ~ sprintf("%.0f%%",   value),
      covariate == "Annual spend"       ~ dollar(value, accuracy = 1),
      covariate == "Monthly app opens"  ~ sprintf("%.0f",     value)
    )
  )

respondent_vs_invited <- ggplot(summary_long, aes(x = value, y = 1)) +
  geom_line(aes(group = covariate), colour = "grey60", linewidth = 0.8) +
  geom_point(aes(colour = group), size = 4) +
  geom_text(
    aes(label = label, colour = group),
    vjust       = -1.4,
    size        = 3.5,
    fontface    = "bold",
    show.legend = FALSE
  ) +
  scale_colour_manual(
    values = c(
      "Invited (150,000)"   = "grey40",
      "Respondents (1,001)" = "#EF4444"
    )
  ) +
  facet_wrap(~covariate, scales = "free_x", ncol = 1, strip.position = "left") +
  scale_y_continuous(limits = c(0.4, 1.9), breaks = NULL) +
  labs(
    title    = "Respondents differ from the invited population on every observable",
    subtitle = "Group means on the four covariates used in Step 1",
    x        = NULL,
    y        = NULL,
    colour   = NULL
  ) +
  theme_minimal(base_size = 12) +
  theme(
    legend.position    = "top",
    plot.title         = element_text(face = "bold"),
    strip.placement    = "outside",
    strip.text.y.left  = element_text(angle = 0, hjust = 1, face = "bold"),
    panel.grid.major.y = element_blank(),
    panel.grid.minor   = element_blank(),
    axis.text.y        = element_blank(),
    axis.ticks.y       = element_blank(),
    panel.spacing.y    = unit(0.6, "lines")
  )

ggsave(
  filename = "figures/respondent_vs_invited.png",
  plot     = respondent_vs_invited,
  width    = 8,
  height   = 6,
  dpi      = 200
)

cat("Saved figures/respondent_vs_invited.png\n")
